FROM node:11

LABEL "repository"="https://github.com/uqmc/arapiles"
LABEL "homepage"="https://github.com/uqmc/arapiles"

WORKDIR /front
COPY src/front/package*.json ./
RUN npm install
COPY src/front/. .

# Run frontend
CMD [ "npm", "run", "dev" ]
